### ISSUE TITLE
is there any command i can use to view the details of a installed chaincode ,such as the all functions and args of each function in this chaincode?

### ISSUE THREAD

**Issue by mqtusi** [hyperledger/fabric-samples#1054]
i have installed a chaincode into a peer.
is there any command i can use to view the details of a installed chaincode ,such as the all functions and args of each function
in this chaincode?

**Comment by satota2** [comment]
@mqtusi 
If you are using the Contract API for your chaincode implementation, you can use "org.hyperledger.fabric:GetMetadata" query function that will provide the chaincode information including the chaincode functions. 

See the mailing list thread below for details:
https://lists.hyperledger.org/g/fabric/topic/85103256#10272

**Comment by FawazMalik-jjj** [comment]
@mqtusi you can use the following to resolve your issue

peer chaincode getinstalledpackage -n <chaincode_name> -l <language> -p <package_id>


Best Regards

**Comment by mqtusi** [comment]
> @mqtusi If you are using the Contract API for your chaincode implementation, you can use "org.hyperledger.fabric:GetMetadata" query function that will provide the chaincode information including the chaincode functions.
> 
> See the mailing list thread below for details: https://lists.hyperledger.org/g/fabric/topic/85103256#10272

**Thanks  @satota2  ! the result is  what i want,but not by a command like "peer chaincode  <something>"**

**Comment by mqtusi** [comment]
> @mqtusi you can use the following to resolve your issue
> 
> peer chaincode getinstalledpackage -n <chaincode_name> -l -p <package_id>
> 
> Best Regards
 the command you provided will download the chaincode,not view the metadata of a chaincode, thank you all the same for your comment @FawazMalik-jjj

**Comment by FawazMalik-jjj** [comment]
your welcome ! Glad to contribute

**Comment by satota2** [comment]
@mqtusi 
Unfortunately, there is no command that directly supports this function itself...
Currently, the simplest way to invoke this function is with the peer chaincode invoke command as belows.

```bash
peer chaincode query -C mychannel -n basic -c '{"Args":["org.hyperledger.fabric:GetMetadata"]}'
```

**Comment by mqtusi** [comment]
> @mqtusi Unfortunately, there is no command that directly supports this function itself... Currently, the simplest way to invoke this function is with the peer chaincode invoke command as belows.
> 
> ```shell
> peer chaincode query -C mychannel -n basic -c '{"Args":["org.hyperledger.fabric:GetMetadata"]}'
> ```

@satota2   big help ! it works! respect again
