### ISSUE TITLE
Is there a java chaincode sample for external-chaincode mode?

### ISSUE THREAD

**Issue by KaiQiu9527** [hyperledger/fabric-samples#1099]
Hi~
I'm learning the external-chaincode mode, and the sample is in golang. 
Is there any sample for java chaincode?
Thanks!

**Comment by satota2** [comment]
Hello @KaiQiu9527 
`asset-transfer-basic/chaincode-java` sample also supports running as an external chaincode.
https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-java

The following page includes end-to-end instruction for chaincode as a service with test-network.
https://github.com/hyperledger/fabric-samples/blob/main/test-network/CHAINCODE_AS_A_SERVICE_TUTORIAL.md#end-to-end-with-the-the-test-network

**Comment by KaiQiu9527** [comment]
@satota2 Thanks for the info!
Btw, I found a spelling mistake here😊
![image](https://github.com/hyperledger/fabric-samples/assets/16130943/260c9ebc-3fc5-4c6e-ae40-94b089717012)

**Comment by KaiQiu9527** [comment]
> @KaiQiu9527 Thank you for reporting the typo. Do you plan on creating and submitting a patch to fix this typo?

Sure😄

**Comment by satota2** [comment]
I believe the original issue has been resolved, so I close this issue.
