### ISSUE TITLE
Documentation to create a channel is not up to date after change

### ISSUE THREAD

**Issue by jannesklee** [hyperledger/fabric-samples#1131]
Within the documentation to [create a channel using the test network](https://hyperledger-fabric.readthedocs.io/en/latest/create_channel/create_channel_test_net.html) there is said something of *TwoOrgsApplicationGenesis*. I guess it needs to be changed in the documentation since a recent commit (eb16caf3d5adf05f58bd9a63cb91707f4e97b81a) changed the behaviour to create a channel.

**Comment by jannesklee** [comment]
https://github.com/hyperledger/fabric/pull/4528

**Comment by denyeart** [comment]
Doc change done in fabric repository, closing.
