### ISSUE TITLE
Ok, I have figured out what was wrong: I was trying to keep compatibility with the "old" JSON "wallet" format.

### ISSUE THREAD

**Issue by Michaelalmada** [hyperledger/fabric-samples#1139]
Ok, I have figured out what was wrong: I was trying to keep compatibility with the "old" JSON "wallet" format. 
Passing the credentials as a Buffer instead of a string into the `identity` property to the gateway's `connect` function solves the problem.

Here is the code snippet for those who want to keep the compatibility back with the "User.id" JSON wallet file format (assuming 2 env vars: one to configure the wallet path and another the identity name to be used to transact, plus using more or less the same code structure used into `asset-transfer-basic/application-gateway-typescript` sample):

```javascript
const walletPath = process.env.WALLET_PATH || '/opt/node/wallet';
const identity = process.env.IDENTITY || 'Admin';

const walletFile = fs.readFileSync(`${walletPath}/${identity}.id`, 'utf8');
const wallet = JSON.parse(walletFile);

const newIdentity: any = async () => {
    const mspId = wallet.mspId;
    const credentials = Buffer.from(wallet.credentials.certificate); // here is the "gotcha"
    
    return { mspId, credentials };
}

const newSigner: any = async () => {
    const privateKey = crypto.createPrivateKey(wallet.credentials.privateKey);

    return signers.newPrivateKeySigner(privateKey);
}
```

_Originally posted by @jeffbicca in https://github.com/hyperledger/fabric/issues/4358#issuecomment-1696326587_

**Comment by bestbeforetoday** [comment]
Good to hear the issue is solved, and thank you for sharing the solution.
