### ISSUE TITLE
test-network-k8s - tcp [::1]:443: connect: connection refused

### ISSUE THREAD

**Issue by marishlucas** [hyperledger/fabric-samples#1160]
Trying to run the scripts from the [docs](https://github.com/hyperledger/fabric-samples/tree/main/test-network-k8s), i get the following error after starting the network:

Using the Rancher configuration

```sh
./network up
Launching network "test-network":
✅ - Creating namespace "test-network" ...
✅ - Provisioning volume storage ...
✅ - Creating fabric config maps ...
✅ - Initializing TLS certificate Issuers ...
✅ - Launching Fabric CAs ...
⚠️  - Enrolling bootstrap ECert CA users ...
```

Error: POST failure of request: POST https://org0-ca.localho.st:443/enroll
{"hosts":["myhost"],"certificate_request":"-----BEGIN CERTIFICATE REQUEST----- xxx -----END CERTIFICATE REQUEST-----\n","profile":"","crl_override":"","label":"","NotBefore":"0001-01-01T00:00:00Z","NotAfter":"0001-01-01T00:00:00Z","ReturnPrecert":false,"CAName":""}: Post "https://org0-ca.localho.st:443/enroll": dial tcp [::1]:443: connect: connection refused

**Comment by gmisiakoulis** [comment]
Probably, you need to disable IPv6, by issuing these commands:
```bash
    sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
    sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

**Comment by lonelymj** [comment]
![image](https://github.com/hyperledger/fabric-samples/assets/4757324/f97777b0-45be-4366-bb5a-53a6c9e4265e)
k8s must be "Disable Traefik" and "Select the dockerd (moby) container runtime"
