### ISSUE TITLE
An exception is thrown when executing channel.sendTransaction()

### ISSUE THREAD

**Issue by riiyn** [hyperledger/fabric-samples#1172]
I successfully built the 1.4 version test network using the byfn.sh script, and then used the 1.4.13 version fabric-sdk-java to develop the client. After connecting to the test network, an exception was thrown when executing channel.sendTransaction:

Caused by: org.hyperledger.fabric.sdk.exception.TransactionEventException: Received invalid transaction event. Transaction ID *** status 10.

The peer used is peer0.org1.example.com. What may be the cause?

**Comment by bestbeforetoday** [comment]
Fabric's [transaction validation code 10](https://github.com/hyperledger/fabric-protos/blob/46bdf5162bbdad1d5d9b9529194be0a87726f9cb/peer/transaction.proto#L106) corresponds to an endorsement policy failure. For some reason the client did not obtain sufficient endorsements for the transaction proposal to meet the effective endorsement policy for the transaction. There is more information on endorsement policies in the [Fabric documentation](https://hyperledger-fabric.readthedocs.io/en/release-1.4/endorsement-policies.html).

Please note that Fabric v1.4 is long out of support. fabric-sdk-java is also deprecated. Fabric v2.5 is the current long-term support release, and the client application API for use with that Fabric version is the [Fabric Gateway client API](https://hyperledger.github.io/fabric-gateway/), which has implementations in Java, Go and Node (TypeScript / JavaScript). If at all possible, I would strongly recommend moving to these current versions.
