### ISSUE TITLE
Application Gateaway Issue Due to CA Certificate File Related Error

### ISSUE THREAD

**Issue by gokulsan** [hyperledger/fabric-samples#1177]
Hello Team,

I was trying the steps mentioned for the deployment of Asset Transfer Basic Chaincode mentioned below. 
https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic

I could deploy the TypeScript and Go variant of the chaincode successfully. 
However the Application is not starting up due to the following error related to CA certificate. 

Request your help to identify this issue. 

gokulalex@gokulalex-G3-3500:~/Code/fabric/fabric-samples/asset-transfer-basic/application-gateway-typescript$ npm start

> asset-transfer-basic@1.0.0 start
> node dist/app.js

channelName:       mychannel
chaincodeName:     basic
mspId:             Org1MSP
cryptoPath:        /home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com
keyDirectoryPath:  /home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore
certPath:          /home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem
tlsCertPath:       /home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
peerEndpoint:      localhost:7051
peerHostAlias:     peer0.org1.example.com

******** FAILED to run the application: [Error: ENOENT: no such file or directory, open '/home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/gokulalex/Code/fabric/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem'
}

**Comment by bestbeforetoday** [comment]
I suspect you might have created the network using the `test-network/network.sh` command without the `-ca` option mentioned in the [README](https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic#readme). This uses the cryptogen tool instead of the CA to create channel credentials, and the client certificate has a different filename.

PR #1183 should allow the sample client application to work in both cases.
