### ISSUE TITLE
Test-network-k8s network script gets last version Fabric bin files instead of requested version

### ISSUE THREAD

**Issue by amiramte** [hyperledger/fabric-samples#1204]
In Fabric-samples when using test-network-k8s in order to bring up cluster and network , it always downloads the latest version of Fabric binary files regardless of if any versions had been specified by any means. It may lead to unkonwn version compability issues.
To be more detailed about the reason it should be explained that  when the "network" script runs, at the very first stages the function named "check_prereqs"  is called  in which the presence of pre-requirements will be checked. In that function availability of /bin and its inner binary files is checked and in case of absence, the Fabric "bootstrap.sh" from "https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/bootstrap.sh" is used to obtain the binary files and place them to /bin folder. But this "bootstrap.sh" script is called without telling which version of bin files should be grabbed so the latest version will be.
In order to solve this issue I have added two variables to the script call, one for Fabric binaries and one for Fabric CA.

**Comment by denyeart** [comment]
Resolved by https://github.com/hyperledger/fabric-samples/pull/1241
