### ISSUE TITLE
Chaincode only accepts the first contract in the export array - Typescript

### ISSUE THREAD

**Issue by ajiths10** [hyperledger/fabric-samples#1229]
## Chaincode only accept the first contract in the export array.

- I've added **super** to each contract class.

> ![image](https://github.com/hyperledger/fabric-samples/assets/98447451/aa660a94-636b-4233-ae65-8d4b44325013)

>![image](https://github.com/hyperledger/fabric-samples/assets/98447451/debc5b17-390c-4bd9-b152-fc2f954bacef)

- I exported the contracts like this:
>![image](https://github.com/hyperledger/fabric-samples/assets/98447451/a66d4bcb-633f-42de-ac95-d6efc012dd22)

- I have 2 channels - _mychannel_ & _garagecars_

- I deployed the chaincode to both channels using these commands:
>
```
./network.sh deployCC -ccn basic -ccp /home/ajiths/Desktop/chaincode-typescript/ -ccl typescript -ccv 2.0 -c mychannel
/network.sh deployCC -ccn basic -ccp /home/ajiths/Desktop/chaincode-typescript/ -ccl typescript -ccv 2.0 -c garagecars

```

 ### The first contract (AssetTransferContract) is accessible on both channels, but the other ones are not.

### Please advice me.

_Version - Latest_

**Comment by bestbeforetoday** [comment]
The problem might be the way your client application is invoking the smart contract. You need to explicitly request the correct contract within the chaincode package, for example:

```typescript
const assetTransfer = network.getContract("basic", "AssetTransferContract");
const carGarage = network.getContract("basic", "CarGarageTransfer");
```

It seems that one of the contracts — for me, the first in the list — is selected as the default contract. The default contract is the one that will be called if you do not explicitly provide the contract name, for example:

```typescript
const defaultContract = network.getContract("basic");
```

Note that the two contract share the containing chaincode's namespace within the ledger so will have visibility of each other's ledger entries. If you want the ledger state of the two smart contracts to be separate, you should deploy them in separate chaincode packages.

**Comment by ajiths10** [comment]
> The problem might be the way your client application is invoking the smart contract. You need to explicitly request the correct contract within the chaincode package, for example:
> 
> ```ts
> const assetTransfer = network.getContract("basic", "AssetTransferContract");
> const carGarage = network.getContract("basic", "CarGarageContract");
> ```
> 
> It seems that one of the contracts — for me, the first in the list — is selected as the default contract. The default contract is the one that will be called if you do not explicitly provide the contract name, for example:
> 
> ```ts
> const defaultContract = network.getContract("basic");
> ```
> 
> Note that the two contracts share the containing chaincode's namespace within the ledger so will have visibility of each other's ledger entries. If you want the ledger state of the two smart contracts to be separate, you should deploy them in separate chaincode packages.

@bestbeforetoday   **This was the issue. This solved my issue. Thank you.**

I have a suggestion as well. It was very hard to find this information in the community. I think we need to include this information in the documentation.

**Comment by bestbeforetoday** [comment]
@ajiths10 Which bits of information were missing for you? The client application side is documented in the API documentation:

- https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Network.html#getContract

It seems that you discovered how to define multiple contracts OK. Again, this is described in the API documentation:

- https://hyperledger.github.io/fabric-chaincode-node/main/api/tutorial-using-contractinterface.html
- https://hyperledger.github.io/fabric-chaincode-node/main/api/tutorial-deep-dive-contract-interface.html

**Comment by ajiths10** [comment]
> @ajiths10 Which bits of information were missing for you? The client application side is documented in the API documentation:
> 
> * https://hyperledger.github.io/fabric-gateway/main/api/node/interfaces/Network.html#getContract
> 
> It seems that you discovered how to define multiple contracts OK. Again, this is described in the API documentation:
> 
> * https://hyperledger.github.io/fabric-chaincode-node/main/api/tutorial-using-contractinterface.html
> * https://hyperledger.github.io/fabric-chaincode-node/main/api/tutorial-deep-dive-contract-interface.html


I never thought it was on the client side. Anyway, thanks for the support :+1:  . **The issue is resolved, so I'm closing this issue.**
