### ISSUE TITLE
Documentation of test-network-k8s+caliper environment setup procedure

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-samples#1236]
Currently, caliper does not consider connecting to test-network-k8s, and the procedure for doing so is not shown.
Unfortunately, there is currently a gap between the caliper and the test-network-k8s environment, so it is difficult to connect directly.
It would be beneficial for test-network-k8s users to document the steps for bridging this gap and integrating the two.
Related discussion on Discord is [here](https://discord.com/channels/905194001349627914/945796983795384331/1241023819121168448).

The specific gaps are shown below:
- Regarding the chaincode deployment:
  - In test-network-k8s, chaincode is deployed as Chaincode-as-a-Service (CCaaS). You will need to adapt the Caliper chaincodes to this setup by following the documentation or other examples.
  - Specifically, you may need to:
     - Prepare Dockerfiles to create chaincode images for each chaincode.
     - For chaincodes using the Contract API, updating the library version might be sufficient. However, some of Caliper's chaincodes may use old APIs, requiring modifications to run as chaincode servers.

- Regarding the certificate paths:
  - In test-network-k8s, keys and certificates are placed under the build/enrollments folder. Running the rest-easy script generates connection profiles under the  build/fabric-rest-sample-config directory, which are designed for REST API servers running as Kubernetes pods.
  - You may need to:
    -  Adjust the paths in the test-network.yaml to match the correct locations.
Modify the connection profiles generated by rest-easy to match Caliper's requirements or consider running Caliper as a Kubernetes pod.

**Comment by takayuki-nagai** [comment]
I would like to be in charge of creating this document.
