### ISSUE TITLE
incorrect path to MSPdir in configtx.yaml 

### ISSUE THREAD

**Issue by osemuaimiosior** [hyperledger/fabric-samples#1253]
In the configtx.yaml file used to setup the network, the MSPdir path used in the test-network seems to be leading to a wrong path.

I can't find the peerOrganisation folder in the organization folder that holds the msp config.

![Uploading Screenshot 2024-10-06 003301.png…]()

**Comment by osemuaimiosior** [comment]
![Uploading Screenshot 2024-10-06 003301.png…]()

**Comment by bestbeforetoday** [comment]
This folder and its contents should be generated when you create a test network using the `network.sh` script. For example (after downloading Fabric binaries and Docker images using the [Fabric install script](https://hyperledger-fabric.readthedocs.io/en/latest/install.html#download-fabric-samples-docker-images-and-binaries)), changing to the `test-network` directory and running:

```
./network.sh up
```

**Comment by osemuaimiosior** [comment]
Thank you...
