### ISSUE TITLE
CLI to be removed from podman compose files 

### ISSUE THREAD

**Issue by ashishkel** [hyperledger/fabric-samples#1258]
Now that CLI is deprecated, I think we should remove the reference to CLI from the compose files. This is preventing the network from starting when we set CONTAINER_CLI = podman

The file to be changed is given below. 

https://github.com/hyperledger/fabric-samples/blob/main/test-network/compose/podman/podman-compose-test-net.yaml

**Comment by twoGiants** [comment]
Hello @ashishkel! 

I removed the line in the PR I just linked to this issue. 

Best,
Stanislav
