### ISSUE TITLE
This version of "fabric-samples" lacks the "fabric-samples/config" directory, resulting in errors when executing the "fabric-samples/test-network/network.sh up" command.

### ISSUE THREAD

**Issue by cshsu0367** [hyperledger/fabric-samples#1259]
This version of "fabric-samples" lacks the "fabric-samples/config" directory, resulting in the following error when executing the "fabric-samples/test-network/network.sh up" command:

"Peer binary and configuration files not found..
Follow the instructions in the Fabric docs to install the Fabric Binaries:
https://hyperledger-fabric.readthedocs.io/en/latest/install.html"

**Comment by bestbeforetoday** [comment]
What exactly is the issue you are reporting? As described in the Fabric install documentation, you need to run the Fabric installer to get the Fabric binaries (and accompanying config directory), and Docker images. You need to do this before trying to start the test network.
