### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0

### ISSUE THREAD

**Issue by hallowsman** [hyperledger/fabric-samples#1280]
执行命令peer lifecycle chaincode install hyperledger-fabric-contract-java-demo.tar.gz
报错如下：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.9.0:compile (default-compile) on project hyperledger-fabric-contract-java-demo: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

尝试了JDK8 JDK11 JDK17 然后均无法编译成功

**Comment by bestbeforetoday** [comment]
This does not look like any of the samples from this repository. You should report an issue to the owner of the _hyperledger-fabric-contract-java-demo_ smart contract.
