### ISSUE TITLE
test-network-k8s

### ISSUE THREAD

**Issue by itcalvin** [hyperledger/fabric-samples#511]
./network chaincode deploy：

Deploying chaincode "asset-transfer-basic":
✅  - Packaging chaincode folder chaincode/asset-transfer-basic ...
✅  - Transferring chaincode archive to org1 ...
✅  - Installing chaincode for org org1 ...
⚠️ - Launching chaincode container "ghcr.io/hyperledgendary/fabric-ccaas-asset-transfer-basic" ...

![image](https://user-images.githubusercontent.com/11419457/138677989-bde3b709-b159-4889-9c85-10af3da06f3f.png)

**Comment by denyeart** [comment]
Is this still an issue? Next steps?

**Comment by SamYuan1990** [comment]
I suppose we can merge this issue with https://github.com/hyperledger/fabric-samples/pull/528 @itcalvin

**Comment by denyeart** [comment]
Closing!
