### ISSUE TITLE
commercial paper for java contract 

### ISSUE THREAD

**Issue by Wuxiuga** [hyperledger/fabric-samples#526]
I can't use gradle bulid the project?  Do I need to upgrade some dependencies ? the package imported can't be resolved in class.file

**Comment by alfahami** [comment]
No you don't have to.
I've built it with gradle and everything went fine.

**Comment by Wuxiuga** [comment]
I can’t run &nbsp;./gradlew build &nbsp;command successfully refers to tutorial given&nbsp;



发自我的iPhone


------------------ Original ------------------
From: AL-FAHAMI Toihir ***@***.***&gt;
Date: Wed,Nov 3,2021 0:54 AM
To: hyperledger/fabric-samples ***@***.***&gt;
Cc: Wuxiuga ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hyperledger/fabric-samples] commercial paper for java contract (Issue #526)





 
No you don't have to.
 I've built it with gradle and everything went fine.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wuxiuga** [comment]
The package imported from hyperledger.fabric.contract can't be resolved.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/fabric-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyperledger/fabric-samples] commercial paper for java contract  (Issue #526)





 
I just ran it and it is working.
 Give the full error and which project are you talking about? Magnetocorp contract? Digibank contract ..?
 Give more details and informations.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alfahami** [comment]
Provide your class code please.

**Comment by Wuxiuga** [comment]
``/*
 * SPDX-License-Identifier: Apache-2.0
 */

package main.java.org.example;

import org.example.ledgerapi.State;
import org.hyperledger.fabric.contract.annotation.DataType;
import org.hyperledger.fabric.contract.annotation.Property;
import org.json.JSONObject;
import org.json.JSONPropertyIgnore;

import static java.nio.charset.StandardCharsets.UTF_8;

@DataType()
public class CommercialPaper extends State {

    // Enumerate commercial paper state values
    public final static String ISSUED = "ISSUED";
    public final static String TRADING = "TRADING";
    public final static String REDEEMED = "REDEEMED";

    @Property()
    private String state="";

    public String getState() {
        return state;
    }

    public CommercialPaper setState(String state) {
        this.state = state;
        return this;
    }

    @JSONPropertyIgnore()
    public boolean isIssued() {
        return this.state.equals(CommercialPaper.ISSUED);
    }

    @JSONPropertyIgnore()
    public boolean isTrading() {
        return this.state.equals(CommercialPaper.TRADING);
    }

    @JSONPropertyIgnore()
    public boolean isRedeemed() {
        return this.state.equals(CommercialPaper.REDEEMED);
    }

    public CommercialPaper setIssued() {
        this.state = CommercialPaper.ISSUED;
        return this;
    }

    public CommercialPaper setTrading() {
        this.state = CommercialPaper.TRADING;
        return this;
    }

    public CommercialPaper setRedeemed() {
        this.state = CommercialPaper.REDEEMED;
        return this;
    }

    @Property()
    private String paperNumber;

    @Property()
    private String issuer;

    @Property()
    private String issueDateTime;

    @Property()
    private int faceValue;

    @Property()
    private String maturityDateTime;

    @Property()
    private String owner;

    public String getOwner() {
        return owner;
    }

    public CommercialPaper setOwner(String owner) {
        this.owner = owner;
        return this;
    }

    public CommercialPaper() {
        super();
    }

    public CommercialPaper setKey() {
        this.key = State.makeKey(new String[] { this.paperNumber });
        return this;
    }

    public String getPaperNumber() {
        return paperNumber;
    }

    public CommercialPaper setPaperNumber(String paperNumber) {
        this.paperNumber = paperNumber;
        return this;
    }

    public String getIssuer() {
        return issuer;
    }

    public CommercialPaper setIssuer(String issuer) {
        this.issuer = issuer;
        return this;
    }

    public String getIssueDateTime() {
        return issueDateTime;
    }

    public CommercialPaper setIssueDateTime(String issueDateTime) {
        this.issueDateTime = issueDateTime;
        return this;
    }

    public int getFaceValue() {
        return faceValue;
    }

    public CommercialPaper setFaceValue(int faceValue) {
        this.faceValue = faceValue;
        return this;
    }

    public String getMaturityDateTime() {
        return maturityDateTime;
    }

    public CommercialPaper setMaturityDateTime(String maturityDateTime) {
        this.maturityDateTime = maturityDateTime;
        return this;
    }

    @Override
    public String toString() {
        return "Paper::" + this.key + "   " + this.getPaperNumber() + " " + getIssuer() + " " + getFaceValue();
    }

    /**
     * Deserialize a state data to commercial paper
     *
     * @param {Buffer} data to form back into the object
     */
    public static CommercialPaper deserialize(byte[] data) {
        JSONObject json = new JSONObject(new String(data, UTF_8));

        String issuer = json.getString("issuer");
        String paperNumber = json.getString("paperNumber");
        String issueDateTime = json.getString("issueDateTime");
        String maturityDateTime = json.getString("maturityDateTime");
        String owner = json.getString("owner");
        int faceValue = json.getInt("faceValue");
        String state = json.getString("state");        
        return createInstance(issuer, paperNumber, issueDateTime, maturityDateTime, faceValue,owner,state);
    }

    public static byte[] serialize(CommercialPaper paper) {
        return State.serialize(paper);
    }

    /**
     * Factory method to create a commercial paper object
     */
    public static CommercialPaper createInstance(String issuer, String paperNumber, String issueDateTime,
            String maturityDateTime, int faceValue, String owner, String state) {
        return new CommercialPaper().setIssuer(issuer).setPaperNumber(paperNumber).setMaturityDateTime(maturityDateTime)
                .setFaceValue(faceValue).setKey().setIssueDateTime(issueDateTime).setOwner(owner).setState(state);
    }


}
the error:
<img width="1607" alt="截屏2021-11-03 下午7 22 56" src="https://user-images.githubusercontent.com/55292351/140051964-a1c671e7-9f6a-479b-8bf9-68b99f024166.png">

**Comment by alfahami** [comment]
It should be @DataType instead of @dataType
You're code throw a lot of errors.
Change the whole class code to this and see what you got:

`/*
 * SPDX-License-Identifier: Apache-2.0
 */

package org.example;

import static java.nio.charset.StandardCharsets.UTF_8;

import org.example.ledgerapi.State;
import org.hyperledger.fabric.contract.annotation.DataType;
import org.hyperledger.fabric.contract.annotation.Property;
import org.json.JSONObject;
import org.json.JSONPropertyIgnore;

@DataType()
public class CommercialPaper extends State {

    // Enumerate commercial paper state values
    public final static String ISSUED = "ISSUED";
    public final static String TRADING = "TRADING";
    public final static String REDEEMED = "REDEEMED";

    @Property()
    private String state="";

    public String getState() {
        return state;
    }

    public CommercialPaper setState(String state) {
        this.state = state;
        return this;
    }

    @JSONPropertyIgnore()
    public boolean isIssued() {
        return this.state.equals(CommercialPaper.ISSUED);
        
    }

    @JSONPropertyIgnore()
    public boolean isTrading() {
        return this.state.equals(CommercialPaper.TRADING);
        
    }

    @JSONPropertyIgnore()
    public boolean isRedeemed() {
        return this.state.equals(CommercialPaper.REDEEMED);
        
    }

    public CommercialPaper setIssued() {
        this.currentState = 1;
        this.state = CommercialPaper.ISSUED;
        return this;
    }

    public CommercialPaper setTrading() {
        this.currentState = 2;
        this.state = CommercialPaper.TRADING;
        return this;
    }

    public CommercialPaper setRedeemed() {
        this.currentState = 3;
        this.state = CommercialPaper.REDEEMED;
        return this;
    }

    @Property()
    private String paperNumber;

    @Property()
    private String issuer;

    @Property()
    private String issueDateTime;

    @Property()
    private int faceValue;

    @Property()
    private String maturityDateTime;

    @Property()
    private String owner;

    public String getOwner() {
        return owner;
    }

    public CommercialPaper setOwner(String owner) {
        this.owner = owner;
        return this;
    }

    public CommercialPaper() {
        super();
        this.currentState = 0;
    }

    public CommercialPaper setKey() {
        this.key = State.makeKey(new String[] { this.paperNumber });
        return this;
    }

    public String getPaperNumber() {
        return paperNumber;
    }

    public CommercialPaper setPaperNumber(String paperNumber) {
        this.paperNumber = paperNumber;
        return this;
    }

    public String getIssuer() {
        return issuer;
    }

    public CommercialPaper setIssuer(String issuer) {
        this.issuer = issuer;
        return this;
    }

    public String getIssueDateTime() {
        return issueDateTime;
    }

    public CommercialPaper setIssueDateTime(String issueDateTime) {
        this.issueDateTime = issueDateTime;
        return this;
    }

    public int getFaceValue() {
        return faceValue;
    }

    public CommercialPaper setFaceValue(int faceValue) {
        this.faceValue = faceValue;
        return this;
    }

    public String getMaturityDateTime() {
        return maturityDateTime;
    }

    public CommercialPaper setMaturityDateTime(String maturityDateTime) {
        this.maturityDateTime = maturityDateTime;
        return this;
    }

    @Override
    public String toString() {
        return "Paper::" + this.key + "   " + this.getPaperNumber() + " " + getIssuer() + " " + getFaceValue();
    }

    /**
     * Deserialize a state data to commercial paper
     *
     * @param {Buffer} data to form back into the object
     */
    public static CommercialPaper deserialize(byte[] data) {
        JSONObject json = new JSONObject(new String(data, UTF_8));

        String issuer = json.getString("issuer");
        String paperNumber = json.getString("paperNumber");
        String issueDateTime = json.getString("issueDateTime");
        String maturityDateTime = json.getString("maturityDateTime");
        String owner = json.getString("owner");
        int faceValue = json.getInt("faceValue");
        String state = json.getString("state");        
        return createInstance(issuer, paperNumber, issueDateTime, maturityDateTime, faceValue,owner,state);
    }

    public static byte[] serialize(CommercialPaper paper) {
        return State.serialize(paper);
    }

    /**
     * Factory method to create a commercial paper object
     */
    public static CommercialPaper createInstance(String issuer, String paperNumber, String issueDateTime,
            String maturityDateTime, int faceValue, String owner, String state) {
        return new CommercialPaper().setIssuer(issuer).setPaperNumber(paperNumber).setMaturityDateTime(maturityDateTime)
                .setFaceValue(faceValue).setKey().setIssueDateTime(issueDateTime).setOwner(owner).setState(state);
    }


}
`

**Comment by Wuxiuga** [comment]
It's not worked either, and why is @datatypr instead of @Datatype, I think the dependencies in the gradle.build file are wrong .Can you run the sample with no error?


&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hyperledger/fabric-samples"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hyperledger/fabric-samples] commercial paper for java contract  (Issue #526)





 
It should be @datatype instead of @datatype
 You're code throw a lot of errors.
 Change the whole class code to this and see what you got:
 
`/*
  
SPDX-License-Identifier: Apache-2.0
 */
  
package org.example;
 
import static java.nio.charset.StandardCharsets.UTF_8;
 
import org.example.ledgerapi.State;
 import org.hyperledger.fabric.contract.annotation.DataType;
 import org.hyperledger.fabric.contract.annotation.Property;
 import org.json.JSONObject;
 import org.json.JSONPropertyIgnore;
 
@datatype()
 public class CommercialPaper extends State {
 // Enumerate commercial paper state values public final static String ISSUED = "ISSUED"; public final static String TRADING = "TRADING"; public final static String REDEEMED = "REDEEMED"; @Property() private String state=""; public String getState() {     return state; } public CommercialPaper setState(String state) {     this.state = state;     return this; } @JSONPropertyIgnore() public boolean isIssued() {     return this.state.equals(CommercialPaper.ISSUED);      } @JSONPropertyIgnore() public boolean isTrading() {     return this.state.equals(CommercialPaper.TRADING);      } @JSONPropertyIgnore() public boolean isRedeemed() {     return this.state.equals(CommercialPaper.REDEEMED);      } public CommercialPaper setIssued() {     this.currentState = 1;     this.state = CommercialPaper.ISSUED;     return this; } public CommercialPaper setTrading() {     this.currentState = 2;     this.state = CommercialPaper.TRADING;     return this; } public CommercialPaper setRedeemed() {     this.currentState = 3;     this.state = CommercialPaper.REDEEMED;     return this; } @Property() private String paperNumber; @Property() private String issuer; @Property() private String issueDateTime; @Property() private int faceValue; @Property() private String maturityDateTime; @Property() private String owner; public String getOwner() {     return owner; } public CommercialPaper setOwner(String owner) {     this.owner = owner;     return this; } public CommercialPaper() {     super();     this.currentState = 0; } public CommercialPaper setKey() {     this.key = State.makeKey(new String[] { this.paperNumber });     return this; } public String getPaperNumber() {     return paperNumber; } public CommercialPaper setPaperNumber(String paperNumber) {     this.paperNumber = paperNumber;     return this; } public String getIssuer() {     return issuer; } public CommercialPaper setIssuer(String issuer) {     this.issuer = issuer;     return this; } public String getIssueDateTime() {     return issueDateTime; } public CommercialPaper setIssueDateTime(String issueDateTime) {     this.issueDateTime = issueDateTime;     return this; } public int getFaceValue() {     return faceValue; } public CommercialPaper setFaceValue(int faceValue) {     this.faceValue = faceValue;     return this; } public String getMaturityDateTime() {     return maturityDateTime; } public CommercialPaper setMaturityDateTime(String maturityDateTime) {     this.maturityDateTime = maturityDateTime;     return this; } @Override public String toString() {     return "Paper::" + this.key + "   " + this.getPaperNumber() + " " + getIssuer() + " " + getFaceValue(); } /**  * Deserialize a state data to commercial paper  *  * @param {Buffer} data to form back into the object  */ public static CommercialPaper deserialize(byte[] data) {     JSONObject json = new JSONObject(new String(data, UTF_8));     String issuer = json.getString("issuer");     String paperNumber = json.getString("paperNumber");     String issueDateTime = json.getString("issueDateTime");     String maturityDateTime = json.getString("maturityDateTime");     String owner = json.getString("owner");     int faceValue = json.getInt("faceValue");     String state = json.getString("state");             return createInstance(issuer, paperNumber, issueDateTime, maturityDateTime, faceValue,owner,state); } public static byte[] serialize(CommercialPaper paper) {     return State.serialize(paper); } /**  * Factory method to create a commercial paper object  */ public static CommercialPaper createInstance(String issuer, String paperNumber, String issueDateTime,         String maturityDateTime, int faceValue, String owner, String state) {     return new CommercialPaper().setIssuer(issuer).setPaperNumber(paperNumber).setMaturityDateTime(maturityDateTime)             .setFaceValue(faceValue).setKey().setIssueDateTime(issueDateTime).setOwner(owner).setState(state); }  
}
 `
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alfahami** [comment]
Yes, I can run it with no errors.
This is why I find it weird.

**Comment by lehors** [comment]
I just tried this again and don't see any problems either using the jdk version 11 so I'm closing this but feel free to reopen if you are still facing the problem but then please provide info to reproduce it.
