### ISSUE TITLE
Add Example of using Prometheus with a sample Graphana dashboard to test network

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-samples#544]
A useful feature for the test-network would be to be able to start a separate prometheus and grafana setup configured to collect and display metrics for the test network. It will demonstrate how to quickly setup an environment to capture metrics in real time and display them. It should 
- update the test network to generate prometheus metrics
- add the ability to separate start a prometheus and grafana server either in the fabric docker network `test` or as a separate network
- provide a sample prometheus configuration that connects to the fabric test network to collect metrics
- provide a sample grafana dashboard to collect some of the more interesting statistics
- provide a README explaining how to setup this environment

This issue covers test-network only and does not include the nano or K8s samples

**Comment by fraVlaca** [comment]
### TASKS

- [ ] Update test network for compatibility with prometheus --> #542
