### ISSUE TITLE
test-network-k8s: ./network kind error creating cluster in docker desktop MacOs

### ISSUE THREAD

**Issue by knagware9** [hyperledger/fabric-samples#557]
test-network-k8s: ./network kind error creating cluster error in docker desktop macOs.

**Comment by nkaramolegos** [comment]
Same on ubuntu 20.04  
```
Initializing KIND cluster "kind":
⚠️  - Creating cluster "kind" ...
```
I think the error is in line 59 of kind.sh script. The config file of the cluster

**Comment by mbwhite** [comment]
@nkaramolegos there's a debug log file that's created, can you add the contents of that please. Should be called `network-debug.log`

**Comment by nkaramolegos** [comment]
Sorry I forgot to post the error. 
```
Deleting cluster "kind" ...
Creating cluster "kind" ...
ERROR: failed to create cluster: unable to decode config: yaml: unmarshal errors:
  line 20: field kubeProxyMode not found in type v1alpha4.Networking
```

**Comment by mbwhite** [comment]
thanks @nkaramolegos

We've been using kind 0.11.1, with K8S v1.21   

I'll close this - as it looks like it's a kind version prereq... please reraise for any other issues @knagware9 @nkaramolegos

**Comment by knagware9** [comment]
Thanks that issue resolved. Issue was related to KInd version
