### ISSUE TITLE
Error while invoking Init function in chaincode: Cannot use metadata. Metadata did not match schema

### ISSUE THREAD

**Issue by Dimple-Kanwar** [hyperledger/fabric-samples#567]
Hi,
I am trying to deploy a chaincode in my fabric network with init function invoke. My chaincode is getting committed on peers but I am getting an error message while invoking init function. 

Note: I am running my custom chaincode on test-network sample setup.

Please find the following attached screenshot to see the proper error message.

![Screen Capture_select-area_20211220231205](https://user-images.githubusercontent.com/24426975/146809749-d1e37287-fb47-4c80-8067-14ffaa287a4e.png)

Let me know the cause of this error.

**Comment by denyeart** [comment]
@mbwhite any ideas?

**Comment by Dimple-Kanwar** [comment]
@denyeart This error was caused by Peer package included in chaincode. I just removed Peer package and changed returnType of chaincode functions from Peer.Response to (Asset, error). Is there any new change introduced in Peer chaincode package which requires some parameters to be passed? I remember it used to work completely fine when I was working on fabric 1.4 version.

**Comment by mbwhite** [comment]
@Dimple-Kanwar are you able to share your code please that caused the issue.

Are you using the fabric-contract-go ? or fabric-shim-go?
