### ISSUE TITLE
Current stable version according to documentation

### ISSUE THREAD

**Issue by HARDY8118** [hyperledger/fabric-samples#569]
The documentation in accordance with the fabric-samples repository is way old and it is not easy to work with it. For instance the documentation refers to a script `byfn.sh` which does not exists in the repository. This is making it really challenging to work with the documentation provided it is the only official source available as of now.

It would be helpful if the documentation gets updated but it will take a long time so instead can somebody suggest a version which can work fine with the docuementation. And preferable how can I install that.

**Comment by alfahami** [comment]
You're on some old documentation.
Please make sure that you've got the 2.2.x documentation.
Its got all new scripts and is more comprehensible than the 1.1.x yet to be improved.
Check it : https://hyperledger-fabric.readthedocs.io/en/release-2.2/

**Comment by HARDY8118** [comment]
I am sure I am on the right documentation.

If you look in the documentation and the fabric-samples repository, you will find that it does not match.

**Comment by denyeart** [comment]
@HARDY8118 byfn.sh is indeed outdated. If there is current documentation referencing byfn.sh, it needs to be updated or removed. Can you share a link to the document you are looking at?

**Comment by HARDY8118** [comment]
@denyeart @alfahami I'm sorry
I got both the documentations mixed up.
My apologies
