### ISSUE TITLE
The new peer gateway samples only work if test-network is deployed with CAs

### ISSUE THREAD

**Issue by davidkel** [hyperledger/fabric-samples#592]
If you deploy a test-network using cryptogen then the peer gateway samples fail because the name of the certificates and private keys are different when generating the identities via cryptogen to that of the identities generated by a CA and the samples are hardcoded with the CA names

**Comment by shashwot2** [comment]
Hi. I also noticed this. Are you using any workarounds currently?

**Comment by davidkel** [comment]
@shashwot2 you would either have to change the sample code to reference the right file, or bring up testnetwork with cas

**Comment by shashwot2** [comment]
That makes sense. Thanks!

**Comment by nikhil550** [comment]
I think encouraging people to bring up the test network with CAs is a good thing. I remember we thought about removing cryptogen altogether when the sample was created.

**Comment by bestbeforetoday** [comment]
I think PR #1183 resolves this issue.
