### ISSUE TITLE
New Feature proposal - Token-ERC-721 in GO

### ISSUE THREAD

**Issue by msalimbene** [hyperledger/fabric-samples#623]
Hello,

I've translated the code from token-erc-721 from JS (the only version available now) to golang. I got a full implementation, along with unit tests. I kept the same comments as in the JS version, and following the README.md instructions, anyone could choose whether to use JS or GO. I have the code ready and fully tested with said instructions.

I'd like to contribute this code, how can I proceed?
Thank you

**Comment by lehors** [comment]
PR #625
