### ISSUE TITLE
jq not found while running samples

### ISSUE THREAD

**Issue by eugenelet** [hyperledger/fabric-samples#648]
Hi, I'm sure that `jq` is installed in my system, but whenever I try to launch the test network using `./network.sh up createChannel -c mychannel -ca` as in https://hyperledger-fabric.readthedocs.io/en/release-2.4/write_first_app.html, it always shows the error of having `jq` not found, e.g. `scripts/configUpdate.sh: line 29: jq: command not found`. Is  there anything that i'm missing? Thanks!

**Comment by eugenelet** [comment]
@mbwhite Thanks for the reply. I've done that, `jq` is found system-wide hence I was checking if there's any part of the code isolates the internal environment from the system's environment. Couldn't find the root cause of the problem. The strange thing is, after deleting `fabric-samples` and re-pulling the entire project for setup, everything seems to run fine. Still puzzled with the source of the original problem.

**Comment by mbwhite** [comment]
very puzzling.. wonder if it might be related to the shell that's being used.

**Comment by lehors** [comment]
@eugenelet I will close this issue but feel free to reopen if you are facing the problem again. Thanks.
