### ISSUE TITLE
[Good Issue First] Unable to add new organization using script "addOrg3.sh"

### ISSUE THREAD

**Issue by parhampr** [hyperledger/fabric-samples#664]
I am using fabric-samples -> test-network to establish the hyperledger fabric network.
The following error comes up when trying to add a new organization to the existing running hyperledger fabric network. 
```
Bringing up Org3 peer
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker/docker-compose-org3.yaml'
ERROR !!!! Unable to start Org3 network
```
Environment:
Windows 11 OS
WSL2 - Ubuntu
Fabric Samples - Latest version: 2.2.4

**Comment by davidkel** [comment]
@parhampr thanks for raising, this issue should now be fixed
