### ISSUE TITLE
#ERR instantiate the chaincode

### ISSUE THREAD

**Issue by NguyenDOanNhan** [hyperledger/fabric-samples#681]
Step: Install and run test chaincode
https://catalog.us-east-1.prod.workshops.aws/workshops/ce1e960e-a811-475f-a221-2afcf57e386a/en-US/02-set-up-a-fabric-client/05-configure-client/08-install-and-run-chaincode

Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error in simulation: could not launch chaincode testcc:v0: chaincode registration failed: container exited with 1

**Comment by bestbeforetoday** [comment]
I don't think this community / repository can address issues running third-party workshop material. This should be addressed to the authors.
