### ISSUE TITLE
Rest-API-Typescript generate environment issue

### ISSUE THREAD

**Issue by pradeepranasinghe** [hyperledger/fabric-samples#687]
I'm unable to find the correct instructions to generate the environment for rest server on version 2  release 1.4.4

TEST_NETWORK_HOME=$HOME/fabric-samples/test-network AS_LOCAL_HOST=false npm run generateEnv

/Users/pradeep.ranasinghe/dev/fabric-samples
192-168-1-15:fabric-samples pradeep.ranasinghe$ cd test-network
192-168-1-15:test-network pradeep.ranasinghe$ ./setOrgEnv.sh 
./setOrgEnv.sh: line 24: ${ORG,,}: bad substitution
192-168-1-15:test-network pradeep.ranasinghe$

**Comment by pradeepranasinghe** [comment]
This issue is resolved now.

**Comment by BushraCloud** [comment]
hi,
I'm having the same issue how did you solve it?

**Comment by jslivane** [comment]
@BushraCloud  Upgrade your bash! ( By https://hybriddbablog.com/2021/01/25/bash-bad-substitution-upgrade-your-bash-version/ )
