### ISSUE TITLE
Need to downgrade to golang v1.13 to starting chaincode on the channel for fabric v2.2

### ISSUE THREAD

**Issue by hanstcs** [hyperledger/fabric-samples#688]
Unable to start chaincode because the go version default set to `1.14`. I was able to start chaincode after downgrade the golang version to `1.13` inside `asset-transfer-basic/chaincode-go/go.mod`

**Comment by bestbeforetoday** [comment]
The chaincode samples in the main branch are currently all working correctly. Closing since this issue appears to now be resolved.
