### ISSUE TITLE
Need to upgrade docker composer compatibility?  

### ISSUE THREAD

**Issue by lucky-gru** [hyperledger/fabric-samples#730]
https://github.com/hyperledger/fabric-samples/blob/f2fbfa410f8903ce047fb369377e4d9e82dee2d5/test-network/network.sh#L32

docker compose v2.x's base command is `docker compose`, not docker-compose
After updaiting ${CONTAINER_CLI}-compose to ${CONTAINER_CLI} compose, it worked perfectly in my side.

**Comment by davidkel** [comment]
That capability is only available in Docker Desktop, not Docker CLI which is what linux uses (so linux users, any build pipelines etc) and even though Docker plan to release Docker Desktop for linux I don't think that making it a requirement to move to docker desktop for linux would be the right thing to do.

**Comment by Mars-Shen** [comment]
same problem here, thanks for your infomation
