### ISSUE TITLE
Commercial paper tutorial link is broken

### ISSUE THREAD

**Issue by ryjones** [hyperledger/fabric-samples#740]
Visit the link https://github.com/hyperledger/fabric-samples this .
Now click on "Commercial paper tutorial" link as mentioned below
https://hyperledger-fabric.readthedocs.io/en/latest/tutorial/commercial_paper.html
we will be redirected to Reads the Docs " SORRY This page does not exist yet. " Error

**Comment by nikhil550** [comment]
The commercial paper sample is no longer best practice in terms of connecting to networks using the SDK. The Fabric gateway has changed that. That is why the tutorial was removed. Would it be best if we removed the sample as well?

**Comment by ryjones** [comment]
@nikhil550 done - PR updated

**Comment by lehors** [comment]
Arguably we could instead point to the tutorial referencing the appropriate version of the documentation instead of "latest".

**Comment by lehors** [comment]
This: https://hyperledger-fabric.readthedocs.io/en/release-2.3/tutorial/commercial_paper.html
