### ISSUE TITLE
Disabling Cache

### ISSUE THREAD

**Issue by Joao-Parente** [hyperledger/fabric-samples#741]
So I want to disable the cache to be sure that the query hits the database, so  I went to the file "fabric-samples/test-network/compose/docker/peercfg/core.yaml" and changed the value CacheSize from 64 to 0 like it says in the comment: 
```
      # CacheSize denotes the maximum mega bytes (MB) to be allocated for the in-memory state
       # cache. Note that CacheSize needs to be a multiple of 32 MB. If it is not a multiple
       # of 32 MB, the peer would round the size to the next multiple of 32 MB.
       # To disable the cache, 0 MB needs to be assigned to the cacheSize."
```
but now when I deploy the chaincode it throws this error:
"Chaincode installation on peer0.org1 has failed
Deploying chaincode failed
Error: error getting endorser client for invoke: endorser client failed to connect to localhost:7051: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7051: connect: connection refused"

Commands used:
``` 
./network.sh down
./network.sh up createChannel -s couchdb
./network.sh deployCC -ccn ledger -ccp ../asset-transfer-ledger-queries/chaincode-go/ -ccl go -ccep "OR('Org1MSP.peer','Org2MSP.peer')"
```
If I reset the cacheSize value to 64 it all works.

**Comment by bestbeforetoday** [comment]
Using Fabric v3.0.0, I tried setting `cacheSize` to `0` in `test-network/compose/docker/peercfg/core.yaml`, as you describe. I then started the test-network (using CouchDB), deployed the asset-transfer-basic Go chaincode, and invoked the chaincode using the Go client application. This worked for me without error. The commands I ran were:

- `./network.sh down`
- `./network.sh up createChannel -c mychannel -ca -s couchdb`
- `./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-go/ -ccl go`
- `cd ../asset-transfer-basic/application-gateway-go`
- `go run .`

I tried the same without specifying CouchDB using both Raft and BFT ordering service. This also worked without error.
