### ISSUE TITLE
ShimTest will be removed in a future release. Future development should make use of the ChaincodeStub Interface for generating mocks

### ISSUE THREAD

**Issue by hxx258456** [hyperledger/fabric-samples#754]
Why are the official unit test examples still in use?

**Comment by bestbeforetoday** [comment]
Thank you for reporting the issue. No current sample code makes use of the shimtest package (which was removed in [fabric-chaincode-go@v2.0.0](https://github.com/hyperledger/fabric-chaincode-go/releases/tag/v2.0.0)).
