### ISSUE TITLE
getting error while submit transaction throgh go client

### ISSUE THREAD

**Issue by Shweta-hlf** [hyperledger/fabric-samples#785]
Hi Team,

I am trying to  submit fabcar chaincode transaction using app and connect.go script
(https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-events/application-gateway-go/app.go)

But getting error 
**Failed to submit transaction: rpc error: code = Unimplemented desc = unknown service gateway.Gateway**

Kindly suggest

**Comment by davidkel** [comment]
the application-gateway-go sample requires a hyperledger fabric 2.4 network as the Gateway service is a new feature for that release. The https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-events/application-javascript is the only sample that will work with older versions of hyperledger fabric.

**Comment by Shweta-hlf** [comment]
Thanks for reply.I got it.
