### ISSUE TITLE
npm install not generating package.json file

### ISSUE THREAD

**Issue by jaideepkaur** [hyperledger/fabric-samples#819]
jaideep@DESKTOP-4NDC02C:~/fabric/src/github.com/jaideep/fabric-samples/asset-transfer-basic/application-gateway-go$ npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/jaideep/fabric/src/github.com/jaideep/fabric-samples/asset-transfer-basic/application-gateway-go/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/jaideep/fabric/src/github.com/jaideep/fabric-samples/asset-transfer-basic/application-gateway-go/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jaideep/.npm/_logs/2022-08-25T12_24_53_280Z-debug-0.log

**Comment by jt-nti** [comment]
Hi @jaideepkaur, it looks like you ran `npm install` in the Go sample directory. Try in the `fabric-samples/asset-transfer-basic/application-gateway-typescript` directory instead.
