### ISSUE TITLE
Can chaincode call other chaincode?

### ISSUE THREAD

**Issue by lluckydog** [hyperledger/fabric-samples#857]
Chaincode can be seen as smart contract, but in Ethereum there may have smart contract call other contract. Is it possible to call other chaincode in Fabric if a peer install two chaincode in the same channel? If possible, how can I write a chaincode like this?

**Comment by lcl1024** [comment]
Of course, you can. see [shim.ChaincodeStubInterface](https://github.com/hyperledger/fabric-chaincode-go/blob/main/shim/interfaces.go#L74)

**Comment by bestbeforetoday** [comment]
Closing as this question is answered above.
