### ISSUE TITLE
Why are there multiple different configtx required to create a channel in the docker test network?

### ISSUE THREAD

**Issue by ajbeach2** [hyperledger/fabric-samples#894]
I am trying to understand the configuration of the test-network. It appears as though, to create a channel, there are two separate configtx.yaml files that are required by the test-network createChannel.sh script.

The first config:
https://github.com/hyperledger/fabric-samples/blob/main/test-network/configtx/configtx.yaml

Defines the organizations:
- OrdererOrg
- Org1
- Org2

This config used used here:
https://github.com/hyperledger/fabric-samples/blob/main/test-network/scripts/createChannel.sh#L80

Which is then used to create the genesis block.
https://github.com/hyperledger/fabric-samples/blob/main/test-network/scripts/createChannel.sh#L30

However, to actually create the channel, and for the peers to join the channel
this root level config/configtx.yaml is used:

https://github.com/hyperledger/fabric-samples/blob/main/test-network/scripts/createChannel.sh#L86

These commands are using the root level config/configtx.yaml
https://github.com/hyperledger/fabric-samples/blob/8d0e632d8646a59cb553360b35886125810ba44f/test-network/scripts/createChannel.sh#L91
https://github.com/hyperledger/fabric-samples/blob/8d0e632d8646a59cb553360b35886125810ba44f/test-network/scripts/createChannel.sh#L96

This configtx.yaml, is downloaded by the install-fabric.sh script,
and its contents are this:
https://github.com/hyperledger/fabric/blob/main/sampleconfig/configtx.yaml

This configtx defines the following orgs:
-  SampleOrg

How does this even work? The root level configtx.yaml doesn't include either org1, org2, or the orderer used in the test-network/configtx/configtx.yaml which is mounted inside all of the peer containers running in the test network.

What is the purpose of the SampleOrg in the top level config?

Why is  the top level config not included in source control of the samples repo?

**Comment by denyeart** [comment]
config/configtx.yaml is never used by test-network. The SampleOrg exists in the default configtx.yaml for people doing simple trials without test-network, but again, it is never used by test-network.

`FABRIC_CFG_PATH=$PWD/../config/` is set so that during the channel join, the `peer channel join` command can use the default config/core.yaml to set the peer client default properties.

**Comment by ajbeach2** [comment]
> config/configtx.yaml is never used by test-network. The SampleOrg exists in the default configtx.yaml for people doing simple trials without test-network, but again, it is never used by test-network.

this is not true. If you remove the config/confif.tx the createChannel scripts fail.

**Comment by ajbeach2** [comment]
It simply doesn't make sense to have 2 configtx.yaml files, if one is used only for peer joining, and an entirely different one for the peer containers. Why wouldn't the peer's configs be used to also join the channel? Wouldn't this simply the setup scripts? You also wouldn't need a separate step to download the binary and config files from the install scripts

**Comment by ajbeach2** [comment]
> FABRIC_CFG_PATH=$PWD/../config/ is set so that during the channel join, the peer channel join command can use the default config/core.yaml to set the peer client default properties.

What properties are required for joining the channel that differ from the properties in the configtx.yaml that is mounted in the peer containers?
