### ISSUE TITLE
Tutorial leads to failure in channel creation using osnadmin

### ISSUE THREAD

**Issue by DeepikaKaranji** [hyperledger/fabric-samples#896]
https://hyperledger-fabric.readthedocs.io/en/release-2.3/create_channel/create_channel_test_net.html

To create a channel, tutorial mentions the following command:
`osnadmin channel join --channelID channel1 --config-block ./channel-artifacts/channel1.block -o localhost:7053 --ca-file "$ORDERER_CA" --client-cert "$ORDERER_ADMIN_TLS_SIGN_CERT" --client-key "$ORDERER_ADMIN_TLS_PRIVATE_KEY"`

Executing this command results in the below error:
`osnadmin: error: unknown long flag '--channelID', try --help`

The correct command is:
`osnadmin channel join --channel-id channel1 --config-block ./channel-artifacts/channel1.block -o localhost:7053 --ca-file "$ORDERER_CA" --client-cert "$ORDERER_ADMIN_TLS_SIGN_CERT" --client-key "$ORDERER_ADMIN_TLS_PRIVATE_KEY"
`

And on successful run, the output will be something like:
```
Status: 201
{
        "name": "channel1",
        "url": "/participation/v1/channels/channel1",
        "consensusRelation": "consenter",
        "status": "active",
        "height": 1
}
```

**Comment by denyeart** [comment]
`--channelID` is correct on v2.3.1 and above.
