### ISSUE TITLE
vendor dependencies error

### ISSUE THREAD

**Issue by yougotitasdfg** [hyperledger/fabric-samples#904]
when I try to use this command in Ubuntu, this error message keeps getting up.But when I try to open the curl in google, it works fine.I don't know why, please help.
victor@Victor:~/go/src/github.com/yougotitasdfg/fabric-samples/asset-transfer-basic/chaincode-go$ GO111MODULE=on go mod vendor
go: downloading github.com/hyperledger/fabric-contract-api-go v1.2.0
go: downloading github.com/hyperledger/fabric-chaincode-go v0.0.0-20220720122508-9207360bbddd
go: downloading github.com/hyperledger/fabric-protos-go v0.0.0-20220613214546-bf864f01d75e
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/stretchr/testify v1.8.0
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go imports
        github.com/hyperledger/fabric-contract-api-go/contractapi: github.com/hyperledger/fabric-contract-api-go@v1.2.0: Get "https://proxy.golang.org/github.com/hyperledger/fabric-contract-api-go/@v/v1.2.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode/mocks imports
        github.com/hyperledger/fabric-chaincode-go/pkg/cid: github.com/hyperledger/fabric-chaincode-go@v0.0.0-20220720122508-9207360bbddd: Get "https://proxy.golang.org/github.com/hyperledger/fabric-chaincode-go/@v/v0.0.0-20220720122508-9207360bbddd.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode/mocks imports
        github.com/hyperledger/fabric-chaincode-go/shim: github.com/hyperledger/fabric-chaincode-go@v0.0.0-20220720122508-9207360bbddd: Get "https://proxy.golang.org/github.com/hyperledger/fabric-chaincode-go/@v/v0.0.0-20220720122508-9207360bbddd.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode/mocks imports
        github.com/hyperledger/fabric-protos-go/ledger/queryresult: github.com/hyperledger/fabric-protos-go@v0.0.0-20220613214546-bf864f01d75e: Get "https://proxy.golang.org/github.com/hyperledger/fabric-protos-go/@v/v0.0.0-20220613214546-bf864f01d75e.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode/mocks imports
        github.com/hyperledger/fabric-protos-go/peer: github.com/hyperledger/fabric-protos-go@v0.0.0-20220613214546-bf864f01d75e: Get "https://proxy.golang.org/github.com/hyperledger/fabric-protos-go/@v/v0.0.0-20220613214546-bf864f01d75e.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode/mocks imports
        google.golang.org/protobuf/types/known/timestamppb: google.golang.org/protobuf@v1.28.0: Get "https://proxy.golang.org/google.golang.org/protobuf/@v/v1.28.0.zip": dial tcp 142.251.42.241:443: i/o timeout
github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode tested by
        github.com/hyperledger/fabric-samples/asset-transfer-basic/chaincode-go/chaincode.test imports
        github.com/stretchr/testify/require: github.com/stretchr/testify@v1.8.0: Get "https://proxy.golang.org/github.com/stretchr/testify/@v/v1.8.0.zip": dial tcp 142.251.42.241:443: i/o timeout

**Comment by bestbeforetoday** [comment]
This looks like it might be a networking issue; either a firewall or outage preventing access to the default Go module proxy (proxy.golang.org). See [here](https://go.dev/ref/mod#module-proxy) for details on Go module proxy configuration. I cannot reproduce this issue locally.
