### ISSUE TITLE
npm commands for asset-transfer-basic/chaincode-typescript fail

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-samples#934]
`npm ci` and `npm run build` for the latest `asset-transfer-basic/chaincode-typescript` seem to fail.

## npm ci fails

`npm ci` fails as shown in the output below.
The reason seems to be that the latest `npm-shrinkwrap.json` is empty and/or out of sync with `package.json`.

```bash
$ cd asset-transfer-basic/chaincode-typescript
$ npm ci
npm WARN ancient lockfile 
npm WARN ancient lockfile The npm-shrinkwrap.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile 
npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile 
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
...
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-02-16T04_34_30_386Z-debug-0.log
```

## npm run build fails

`npm run build` fails with a type error.
According to [this Issue](https://github.com/winstonjs/logform/commit/20213e15dd6cde9c7227a6aee12648c72d468f7c), it needs to be upgraded to a higher version of TypeScript or use an older version of logform.

```bash
$ npm install
$ npm run build
> asset-transfer-basic@1.0.0 build
> tsc

node_modules/logform/index.d.ts:14:4 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

14   [key: string | symbol]: any;
      ~~~


Found 1 error.
```

**Comment by ryjones** [comment]
@denyeart @bestbeforetoday

**Comment by bestbeforetoday** [comment]
Just note that I am not a maintainer of this repository. You might want to tag @mbwhite instead.

**Comment by ryjones** [comment]
@mbwhite

**Comment by mbwhite** [comment]
https://github.com/hyperledger/fabric-samples/pull/1018

**Comment by ryjones** [comment]
@satota2 is this issue fixed?

**Comment by thejungwon** [comment]
> 

The merge hasn't happened yet, but it is possible to update the TypeScript version to a version above 4.4, as demonstrated in this pull request: https://github.com/hyperledger/fabric-samples/pull/935.
