### ISSUE TITLE
Fabric版本与Go版本的兼容性问题

### ISSUE THREAD

**Issue by treeforest** [hyperledger/fabric-samples#939]
当使用Go 1.19 及以上版本运行 fabric-samples 2.2.x  的示例 asset-transfer-basic/application-go 时，将会产生证书错误的问题。将Go版本替换成 1.17.12 后方能正常运行（这个问题困扰了我好几天），希望能在示例中注明Go的版本建议。

**Comment by bestbeforetoday** [comment]
Translation from Google translate:

> When running the fabric-samples 2.2.x sample asset-transfer-basic/application-go with Go 1.19 and above, a certificate error will occur. Replace the Go version with 1.17.12 to make it work (this problem has troubled me for several days). I hope the Go version recommendation can be noted in the example.

**Comment by treeforest** [comment]
收到了，谢谢~~

**Comment by bestbeforetoday** [comment]
I just tried running the asset-transfer-basic/application-go sample from the latest state of the [release-2.2](https://github.com/hyperledger/fabric-samples/tree/release-2.2) branch with Go 1.23.1 and (except for the `go.sum` file being out-of-date and requiring a `go mod tidy`) the sample run successfully for me.
