### ISSUE TITLE
Add two phase commit asset transfer sample

### ISSUE THREAD

**Issue by jt-nti** [hyperledger/fabric-samples#997]
I'm thinking about using Fabric in a sample scenario which involves a coordinated unit of work. It seems likely that there would be other use cases, such as CBDC, that would require two phase commit support, and an asset transfer sample demonstrating how that would be possible with the latest version of Hyperledger Fabric would be really useful.

**Comment by bestbeforetoday** [comment]
Closing as as not planned since there has been no community interest in developing this sample.
